"""
This module contains the mapping from phonemes to facial expression data.
"""

PHONEME_MAP = {
    'AA': [('lipRightCorner2', 'translateX', 0.7), ('lipLeftCorner2', 'translateX', 0.7), ('jaw', 'translateY', -0.7)],
    'AE': [('jaw', 'translateY', -0.5)],
    'AH': [('jaw', 'translateY', -0.4)],
    'AO': 'AA',
    'AW': ['AO', 'OW'],
    'AY': ['AH', 'Y'],
    'B': [('lipRightCorner2', 'translateX', 0.1), ('lipLeftCorner2', 'translateX', 0.1), ('stickLipsLeft', 'translateY', 1.0), ('stickLipsRight', 'translateY', 1.0), ('jaw', 'translateY', -0.1)],
    'CH': [('lipRightCorner2', 'translateX', 0.3), ('lipLeftCorner2', 'translateX', 0.3), ('upperLip4', 'translateY', 0.2), ('lowerLip4', 'translateY', 0.1), ('upperLip2', 'translateY', 0.2), ('lowerLip2', 'translateY', 0.1), ('upperLipInOutLeft', 'translateY', 1.0), ('lowerLipInOutLeft', 'translateY', 1.0), ('upperLipInOutRight', 'translateY', 1.0), ('lowerLipInOutRight', 'translateY', 1.0), ('mouthInOut', 'translateY', 1.0)],
    'D': [('tongue_rotate', (0, 0, 0, 25)), ('jaw', 'translateY', -0.1)],
    'DH': [('jaw', 'translateY', -0.2), ('tongue_translate', ('translateX', 0.250)), ('tongue_translate', ('translateY', 0.600))],
    'EH': [('jaw', 'translateY', -0.3)],
    'ER': [('lipRightCorner2', 'translateX', 0.2), ('lipLeftCorner2', 'translateX', 0.2), ('upperLipInOutLeft', 'translateY', 1.0), ('lowerLipInOutLeft', 'translateY', 1.0), ('upperLipInOutRight', 'translateY', 1.0), ('lowerLipInOutRight', 'translateY', 1.0), ('mouthInOut', 'translateY', 1.0), ('jaw', 'translateY', -0.1)],
    'EY': 'AE',
    'F': [('lowerLipInOutLeft', 'translateY', -0.6), ('lowerLipInOutRight', 'translateY', -0.6), ('jaw', 'translateY', -0.15)],
    'G': [('jaw', 'translateY', -0.1)],
    'HH': [('lowerLipInOutLeft', 'translateY', 0.3), ('lowerLipInOutRight', 'translateY', 0.3), ('jaw', 'translateY', -0.1)],
    'IH': 'HH',
    'IY': [('tongue_rotate', (0,0,0,0)), ('lipRightCorner2', 'translateX', -0.2), ('lipLeftCorner2', 'translateX', -0.2), ('lowerLipInOutLeft', 'translateY', 1.0), ('lowerLipInOutRight', 'translateY', 1.0), ('jaw', 'translateY', -0.1)],
    'JH': 'CH',
    'K': 'G',
    'L': 'D',
    'M': 'B',
    'N': 'D',
    'NG': ['G', 'N'],
    'OW': [('lipRightCorner2', 'translateX', 0.9), ('lipLeftCorner2', 'translateX', 0.9), ('jaw', 'translateY', -0.5), ('mouthInOut', 'translateY', 0.25), ('upperLipInOutLeft', 'translateY', 1.0), ('lowerLipInOutLeft', 'translateY', 1.0), ('upperLipInOutRight', 'translateY', 1.0), ('lowerLipInOutRight', 'translateY', 1.0)],
    'OY': ['AO', 'Y'],
    'P': 'B',
    'R': 'D',
    'S': [('lipRightCorner2', 'translateX', -0.3), ('lipLeftCorner2', 'translateX', -0.3), ('jaw', 'translateY', -0.1)],
    'SH': 'CH',
    'T': 'D',
    'TH': 'DH',
    'UH': [('lipRightCorner2', 'translateX', 1), ('lipLeftCorner2', 'translateX', 1), ('mouthInOut', 'translateY', 0.1), ('jaw', 'translateY', -0.3)],
    'UW': 'UH',
    'V': 'F',
    'W': 'F',
    'Y': [('lipRightCorner2', 'translateX', -0.1), ('lipLeftCorner2', 'translateX', -0.1), ('jaw', 'translateY', -0.1)],
    'Z': 'S',
    'ZH': 'CH'
}
